spring.application.name=erp_back

spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MariaDB
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

server.port=0
server.ssl.enabled=false

AUTH_PASSWORD=testSecretKeyPourLesTestsUnitairesTresLongue1234567890
AUTH_EXPIRATION_TIME=86400000

cas.server=http://localhost:8080
backend.url=http://localhost:8080
frontend.url=http://localhost:3000
encryption.key=12345678901234567890123456789012
encryption.salt=6d3823720c9d413a
initial.identifier=test
